import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import VideoUpload from '../components/UploadVideo'
import Link from 'next/link'

export default function Home({nextVideo}) {
  return (
    <>
    <div className={styles.container}>
      <Head>
        <title>OurTube</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <VideoUpload />
        <Link className={styles.link} href={"/roulette"} >Roulette</Link>
      </main>
    </div>

    </>
  )
}

export const getServerSideProps = async (context) => {

  const random = await (await fetch("http://localhost/api/catalog")).json();

return {
  props: {
      query: context.query,
      nextVideo: random.id
    },
};
};
