import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import VideoUpload from '../components/UploadVideo'
import Link from 'next/link'
import { getRandomVideo } from '../lib/catalog'

export default function Home() {
  return (
    <>
    <div className={styles.container}>
      <Head>
        <title>OurTube</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <VideoUpload />
        <Link className={styles.link} href={"/roulette"} >Roulette</Link>
        <Link className={styles.link} href={"/videos"} >Videos</Link>
      </main>
    </div>

    </>
  )
}

export const getServerSideProps = async (context) => {


  

return {
  props: {
      query: context.query,
    },
};
};
